### PR TITLE
Add support for libusb callbacks

### PR DESCRIPTION
**Pull request by richo**
I added these by hand, not with bindgen or anything, so let me know if I did anything wrong. I also wasn't sure if you wanted native enums or c_ints so I went with what was already here.

### CODE REVIEW

**Comment by dcuddeback** [comment]
@richo Thanks for submitting this, and sorry for taking so long to respond. I'd love to merge support for the hotplug functionality. I'd like to add an example that uses the added functions. Compiling examples links against the C library, which is enough to catch typos in function names or catch functions that don't exist in older versions of the library. If you want to add an example that prints out hotplug events, I think I could merge this. I realize it's been a long time since you opened this PR. If you've moved on, I understand. I can merge this when I have time to write an example.

**Comment by richo** [comment]
Hi!

No worries, I've definitely missed tons of stuff as well. I appreciate you getting back to me! As far as a testcase, I'm happy to add one. I actually had problems getting this to work (either via this crate, or via some C code that purported to work). Is there any chance you're familiar enough with this to help out? I can definitely add some code that excercises this end to end but I'd like to be more confident that the events not firing is a quirk of my system and not that the code is defective.

Either way, I'll add the example sometime tonight. Thanks again and take care :)

**Comment by richo** [comment]
Ok I figured out the issue with my example code, let me clean it up and add it to this PR. Then if it's ok I'll open a PR on libusb-rs exposing it with a nice API?

**Comment by richo** [comment]
Ok I just added an example that works on my mac at least. I'll make a start on adding these to the -rs crate, thanks for the nudge to get this working.

**Comment by dcuddeback** [comment]
@richo Thanks. I'll work on landing this PR today.

For the -rs crate, I'd avoid trying to do something fancy like making an iterator for hotplug events. I only mention that because I know that sort of thing is tempting to a lot of people, but would waste a lot of time if it's ultimately going to be rejected. I think all that's needed is a simple RAII-style handle to register/deregister callbacks:

```rust
let callback_handle = context.register_callback(|device, event| {
    println!("{:?} {:?}", event, device);
}); // callback is deregistered when `callback_handle` goes out of scope
```

If you run into problems because of context lifetimes, just know that fixing that is on my todo list.

**Comment by dcuddeback** [comment]
@richo I merged this manually with some changes. I found some `const` pointers that should be `mut`. I added `libusb_hotplug_get_user_data()`, but couldn't add it to the example, because it's not present in older versions of the library. I'll wait to push a release until hotplug support is added to libusb-rs, just in case we discover more changes that are needed.

**Comment by richo** [comment]
Thanks so much! Sorry it was a bit of a mess.

I think we're on the same page about what the callback API should look like. I briefly noodled on trying to do something fancy with the user data API but I think it's easier to just let people close over stuff they want. I'm fiddling with what the story should look like for canceling from the closure, but I'm planning to do something fairly minimal. thanks again!

**Comment by richo** [comment]
I've been playing with this on and off, I have something that builds now but I am still tooling around with the API. I'm planning to PR something today or tomorrow that excercises everything, get feedback on the API and then I'll add docs and tests, if that's ok with you?

**Pull request closed without merging**
